columns:  #column names should be in same order as in Dataset
  Item_Identifier: category 
  Item_Weight: float
  Item_Fat_Content: category 
  Item_Visibility: float
  Item_Type: category
  Item_MRP: float
  Outlet_Identifier: category 
  Outlet_Establishment_Year: int  
  Outlet_Size: category 
  Outlet_Location_Type: category
  Outlet_Type: category
  Item_Outlet_Sales:  float

numerical_columns:
  - Item_Weight
  - Item_Visibility
  - Item_MRP

categorical_columns:
  - Item_Identifier
  - Item_Fat_Content
  - Item_Type
  - Outlet_Identifier
  - Outlet_Size
  - Outlet_Location_Type
  - Outlet_Type
  - Outlet_Establishment_Year

target_column: Item_Outlet_Sales

drop_columns:
  - Item_Identifier
